### ISSUE TITLE
请问这些ip-cidr是怎么获取的

### ISSUE THREAD

**Issue by duhd1993** [Geek0x0/Quantumult_Config#1]
谢谢，另外感觉似乎有遗漏

**Comment by Geek0x0** [comment]
🤣大部分是自己抓包获取的，基于联通和电信网络，微信有一些是公众号 API 获取的 IP 地址
如果你有想要补充的可以回复，多谢！

**Comment by duhd1993** [comment]
😂这样子啊，不过应该还是比较全了。
我情况不一样，我是在国外用，我想让微信/支付宝直连。就发现有些ip还是按照GEOIP,CN,PROXY再走。这些地址ASN是属于腾讯/CN的，但ipip查出来地址是香港/美国等。

**Comment by Geek0x0** [comment]
酱紫，我也就不清楚了，没有试验环境
